### PR TITLE
New patterns page

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

No related issue

### Description

This restores a previous version of the patterns page to correctly reflect the right content, as there was a bad merge when resolving a conflict.

### Changelog

**Changed**

- Restored the correct content state of the patterns landing page

### CODE REVIEW

**Comment by JennySanchez** [comment]
The content looks correct to me now. @larahanlon2 Can you double-check before I approve the PR?

**Review by JennySanchez — APPROVED** [review]
Looks good to me.

**Comment by larahanlon2** [comment]
@JennySanchez everything looks good except the cards at the bottom. There should be one only, linking to Carbon patterns. I'll update the file.

**Review by larahanlon2 — APPROVED** [review]
Cards updated. Good to go!

**Comment by JennySanchez** [comment]
Can't wait to see it live on the website!!!

**Comment by larahanlon2** [comment]
It's alive! http://ibm-dotcom-library.mybluemix.net/patterns/

**Pull request merged**
