### PR TITLE
Create in-page navigation

### PR DESCRIPTION
**Pull request by larahanlon2**
### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by oliviaflory — APPROVED** [review]
Looks good to me!

**Review by JennySanchez — APPROVED** [review]
LGTM. Thanks, Lara!

**Comment by wonilsuhibm** [comment]
This looks good to me too. Thank you for the last minute updates @larahanlon2

**Comment by larahanlon2** [comment]
Awesome!! Thank you all @wonilsuhibm @JennySanchez @oliviaflory

**Pull request merged**
