### PR TITLE
Language changes

### PR DESCRIPTION
**Pull request by ghost**
- Design and functional specs should come first, reflecting the usual order of work
- Changing the section title to be more user friendly: from "specification documentation" to "Design and functional specs"

### Related Ticket(s)

https://www.ibm.com/standards/web/ibm-dotcom-library/patterns/content-block-simple

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by wonilsuhibm** [comment]
Just converted this to a draft to gather more input.

**Review by larahanlon2 — CHANGES_REQUESTED** [review]
Hey @wonilsuhibm some feedback on the change:

1. **Specifications** in the title should not have an uppercase S (unless we want every title to be sentence case?)

2. **To reflect the title order** 'Design and functional specs' I wonder should you update the sentence to say 'The design specs and functional specs...' rather than 'The functional specs and design specs...'

3. I noticed that you are giving **title case treatment** to the name of the pattern: Content block — simple. That works, of course, but across the site, all pattern names are set in lowercase. No capitalization at all. To be consistent I'm suggesting to change this to lowercase, too.

Screen Shot 2020-07-28 at 1 34 38 PM

**Comment by wonilsuhibm** [comment]
@larahanlon2 thank you for the comments. All of them make sense. WIll make changes and report back here.

**Comment by JennySanchez** [comment]
@larahanlon2 The name of the pattern: "Content block — simple" that's how we address the pattern title in the design "Specification documentation" section current. Remember we talked about without the cap, the name of the pattern blends in with the sentence? :-)

**Comment by larahanlon2** [comment]
@JennySanchez hey! yep I remember that conversation with you for sure, I just don't see it reflected on the website yet but if you're making those changes across the board then definitely leave the capital in place here.

**Comment by JennySanchez** [comment]
@larahanlon2 Yes, in all the pages published, as far as I can tell between Jacob and I, we always use the cap treatment in the sentence under the "Specification documentation" section.

**Comment by larahanlon2** [comment]
@JennySanchez that's great but the other sections of the page should probably follow the same type styling in that case. If we take `content group — simple` for example, it is set in lowercase in the opening descriptor and Default section of the page but then it's set in quotation marks and Sentence Case in the specification section. I think it would be better if it was consistent throughout.

See below:
Screen Shot 2020-07-28 at 4 58 58 PM
Screen Shot 2020-07-28 at 4 59 02 PM
Screen Shot 2020-07-28 at 4 59 07 PM

**Comment by JennySanchez** [comment]
@larahanlon2 True. That's what I have been thinking about once we start talking. This is the fine detail we discover once we start the publishing process. For now, would you both agree that we should always use the " " and the Cap treatment when calling out the pattern? For example, we will use "Content group — simple" when it's in a sentence across the three areas.

**Comment by wonilsuhibm** [comment]
All changes have been made including the sentence casing of the pattern names in the doc.

**Review by larahanlon2 — APPROVED** [review]
Great!

**Review by JennySanchez — APPROVED** [review]
Thank you both for the work and feedback, Wonil and Lara.

**Pull request merged**
