### PR TITLE
Cs and fcb

### PR DESCRIPTION
**Pull request by JennySanchez**
### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by wonilsuhibm** [comment]
@JennySanchez Thank you. Is it `Feature card block medium` or `Feature card block — medium`?

**Comment by jacobottesen-dgc** [comment]
@wonilsuhibm The correct naming according to airtable is "Feature card block – medium."
Screen Shot 2020-07-29 at 10 31 55 AM

**Comment by wonilsuhibm** [comment]
@jacobottesen-dgc Please make the necessary name changes.

**Comment by jacobottesen-dgc** [comment]
@wonilsuhibm FYI changes are made in this PR https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/556

**Pull request merged**
