### PR TITLE
feat(components): updated to have dynamically manages component overview/gallery views

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

Refs https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/541

### Description

This change adds the component gallery and list views. This is all driven by a component data file which keeps track of all of the data for the corresponding components, as well as status for those given components.

Note, an additional change will be added to drive the page level component development status to also be part of the data rather than hard coded, so that will come in upcoming commits. The gallery view images have also not been finalized, so all are rendering the `NoImage` currently.

### Changelog

**New**

- `ComponentGallery`, `ComponentList`, `ComponentStatus`, and `TagKey`
- Data driven file to track all component data and statuses
- Updated the component overview page to have an `Overview` and `Gallery` tabs.

### CODE REVIEW

**Comment by wonilsuhibm** [comment]
Thank you Jenny and Jeff.

- Should "Key" be "Keys"?
- Should the Keys section come before the Core components section?

**Comment by jeffchew** [comment]
@wonilsuhibm I think it's singular `key`. 

@wonilsuhibm @JennySanchez @jacobottesen-dgc all of the changes are in, waiting for the deploy preview to rebuild. But the additional change I made is that the developer documentation table on all of the pages are now driven by the single source components data, so we only need to update the data in one place now.

**Comment by JennySanchez** [comment]
Hi @jeffchew 

**For the Overview page:**
- The width should be 608 px but not 928 px/full width. Did you make the change because of the long scrolling? And, the need to add the 
- The "New" label is an exciting addition. We might need to add a new column for it. It looks too cramped.
- The Key section, I'd like to see if we can treat it differently but not in a table list, so the two tables can stand out.
- For the Dotcom Shell, the [Masthead](./components/masthead), and [Footer](./components/footer) in the description should be text links and link to the URL (./components/masthead) and (./components/footer) 
Screen Shot 2020-09-23 at 2 20 02 PM
(should be)
Screen Shot 2020-09-23 at 2 23 19 PM

- I also noticed "Lead space &mdash; block" should be "Lead space — block"

**For the Gallery page:**

It looks great and I can't wait to see it live on our website!

**Comment by jeffchew** [comment]
> Hi @jeffchew
> 
> **For the Overview page:**
> 
> * The width should be 608 px but not 928 px/full width. Did you make the change because of the long scrolling? And, the need to add the

I'll fix that, this table is using custom styles (from the Carbon website) so I'll add the `max-width`.

> * The "New" label is an exciting addition. We might need to add a new column for it. It looks too cramped.

This is a direct lift from the Carbon website, and the logic iterates through the flags to show (I'll show you and @jacobottesen-dgc later how it works). 

> * The Key section, I'd like to see if we can treat it differently but not in a table list, so the two tables can stand out.

Also a direct lift from the Carbon website. Should we leave in for now and perhaps tweak the design later?

> * For the Dotcom Shell, the [Masthead](./components/masthead), and [Footer](./components/footer) in the description should be text links and link to the URL (./components/masthead) and (./components/footer)

Will fix this.

>   Screen Shot 2020-09-23 at 2 20 02 PM
>   (should be)
>   Screen Shot 2020-09-23 at 2 23 19 PM
> * I also noticed "Lead space — block" should be "Lead space — block"

Not sure what the difference is, can you explain? 

> **For the Gallery page:**
> 
> It looks great and I can't wait to see it live on our website!

**Comment by jeffchew** [comment]
@JennySanchez @jacobottesen-dgc all changes are in and ready for final review!

**Review by JennySanchez — APPROVED** [review]
Looking great! Thank you, Jeff.

**Pull request merged**
