### PR TITLE
docs(coding): reorder of content

### PR DESCRIPTION
**Pull request by jeffchew**
### Related Ticket(s)

No related issue

### Description

This is a change to the flow of the content on the coding page.

### Changelog

**Changed**

- Coding page content changes

### CODE REVIEW

**Review by ljcarot — COMMENTED** [review]
Under Resources, do you think people will know which of the 4 packages to use or should Resources have a bit more on an introduction of each?

**Comment by jeffchew** [comment]
> Under Resources, do you think people will know which of the 4 packages to use or should Resources have a bit more on an introduction of each?

Good call, let me create a section talking about the different packages

**Comment by ljcarot** [comment]
Looks good @jeffchew !

**Review by kennylam — APPROVED** [review]
Looks good!

**Review by JennySanchez — APPROVED** [review]

**Pull request merged**
